mybatis:
  type-aliases-package: com.bilibili.majiang.demo.model.User
pagehelper:
  helperDialect: h2
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#在格式：logging.level.Mapper类的包=debug  会在控制台打印出sql语句

