spring:
  datasource:
    url: jdbc:h2:~/majiang
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
    flyway:
      baseline-on-migrate: true
      #是否开启flyway
      enabled: true